//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMO_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderGoods
    {
        public int GoodsId { get; set; }
        public int UserId { get; set; }
        public int Amount { get; set; }
        public int OrderGoodsId { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Users Users { get; set; }
    }
}
